### ISSUE TITLE
Typescript references not resolved in Visual Studio

### ISSUE THREAD

**Issue by AndyCross** [Microsoft/PowerBI-visuals#12]
Opening up a file in this project in Visual Studio results in a lot of unresolved references - even when the `gulp build` process is successful. 

*I'm a big fan of the type system you get in Typescript especially as it aids code abstraction discovery in a new code base.* Do we need `/// <reference path='path/to/file' />` added to the files, or is this a result of the recent restructuring of the projects?

**Example**

![image](https://cloud.githubusercontent.com/assets/773613/9131942/db39fbc0-3ce7-11e5-92f0-9a274b1d9bb2.png)

**Comment by AndyCross** [comment]
I'd be happy if Visual Studio isn't the way to go but you could share your IDE. Are you using VS Code?

**Comment by spatney** [comment]
No, VS 2015 is the way to go. The problem here I believe is that VS doesn't automatically search for references if you already have some. Removing them would fix the intellisense issue, but would result in the compiled JS file be concatenated in the wrong order, which will cause run time errors, since we have static initializers in the code that are order dependent. We think we've a fix for this issue, and are just running it thru the paces to validate it, and will have a fix out soon. Thank you for your patience.

**Comment by AndyCross** [comment]
Thanks for the clear insight. I'm eager to create a new visualization!
________________________________

**Comment by spatney** [comment]
This is now fixed in the latest [release](https://github.com/Microsoft/PowerBI-visuals/releases/tag/v0.2.1). Be sure to build the solution first, in-order for the references to resolve correctly.
