### ISSUE TITLE
Playground app lacks examples of interacting IVisuals

### ISSUE THREAD

**Issue by UncleDolan** [Microsoft/PowerBI-visuals#139]
I have been trying to figure out how the selection of one IVisual could affect another.
For example, if I have a line chart and also a pie chart backed by the same data and I click on one of the series on the line chart, the pie chart should also get updated. 

According to "Hello IVisual" at "https://github.com/Microsoft/PowerBI-visuals/wiki/Hello-IVisual", on step six, it says "There isn't much work required other than to call select on the selection manager with the selector for a datapoint. The host will take care of performing cross filtering, etc and send updates to the other visuals."

I tried to trace the code to figure out how exactly the host (DefaultVisualHostServices) is doing the cross filtering and updating other visuals but it seems at the end the host calls "onSelect" which is an empty function:
DefaultVisualHostServices.prototype.onSelect = function () { };

It seems like playground app does not have any sample where IVisual-to-IVisual interaction happens, so it is rather hard for me to learn what the selection model is and how cross-filtering happens. 

Can anyone explain DefaultVisualHostServices or show me a sample of how I can update one IVisual by interacting with another?

Thanks.

**Comment by spatney** [comment]
Hey. The default service doesn't implement any of the interactivity because the playground only shows one visual at a time. The only way to test visual to visual interaction is from within power bi. You can go to powerbi.com -> settings -> dev tools. The developer tools editor will open up, and you can add your visual's code to the editor, run it, pop back into a report and try out your interactions.

That being said, we will in the future allow you to do this from within the playground. Let me know if you have any other questions.
