### ISSUE TITLE
Unable to use JqueryUI or JQuery Dependent Library

### ISSUE THREAD

**Issue by youranupama** [Microsoft/PowerBI-visuals#158]
I tried adding JqueryUI with typings and other third party library which is dependent on Jquery. I am providing the following sequence in my TSConfig.json
"files": [
    ".api/v1.4.0/PowerBI-visuals.d.ts",    
    "node_modules/d3/d3.min.js",
    "node_modules/jquery/dist/jquery.js",
    "node_modules/jqueryui/jquery-ui.js",
    "node_modules/lodash/lodash.js",        
    "typings/index.d.ts",
    "src/visual.ts"
  ]
When I load the Visual, it does not load anything and console have error "Uncaught TypeError: Cannot read property 'ui' of undefined"
After removing the JqueryUI reference, the visual loads fine. This is a template Visual and not code is added to it yet except for D3 reference that works fine.

**Comment by ignatvilesov** [comment]
@youranupama This problem is related to the fact that Power BI creates a fake of the main window object for security reasons.
Could you please follow these steps below to apply the workaround:
1. Move ```.js``` files to the ```externalJS``` property of ```pbiviz.json```
2. Create a new JavaScript file in your custom visual (let's call it ```jQueryAdapter.js```)
3. Include the following code to the created file:
```javascript
var jQuery = typeof jQuery !== 'undefined'
    ? jQuery
    : window['$'];
```
4. Include the created file to the ```externalJS``` right after ```jquery.js```

Please note it's temporary workaround and we'll improve it soon.

**Comment by youranupama** [comment]
Great. Thanks. It solves this problem
