### ISSUE TITLE
Ajax request inside Custom Visual

### ISSUE THREAD

**Issue by EdwinStraver** [microsoft/PowerBI-visuals#177]
Is it possible to make a REST call or AJAX call inside the "update" method of a custom visual?
When I try, I get a permission issue, which makes me think cross domain requests are not allowed?
Is there a way to get around this?

**Comment by nikhilkabbin** [comment]
@EdwinStraver If I am not wrong Power-BI will not allow you to make HTTP requests, it only allows HTTPS requests.

**Comment by EdwinStraver** [comment]
Thanks for the reply!
I am actually trying to make calls to a REST api that is located at HTTPS, not HTTP.  So that doesn't seem to be the issue, however. 
Do you perhaps have any recommendations on how to go about this?

**Comment by jhegele** [comment]
I ran into this same issue trying to use jQuery to make a request. It's a CORS issue and I'm pretty certain that it an issue with how the server component of the Power BI developer tools is configured. I was trying to POST to my company's API (which is configured to allow cross-origin requests) but getting failures. Here are my outgoing headers (with the authority and path modified to remove my company's info):

```:authority:api.mycompany.com
:method:OPTIONS
:path:/path/to/endpoint
:scheme:https
accept:*/*
accept-encoding:gzip, deflate, sdch, br
accept-language:en-US,en;q=0.8
access-control-request-headers:authorization
access-control-request-method:POST
origin:null
user-agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36```

I have to send an auth token to validate against the API so, using jQuery, it triggers a preflight OPTIONS request which is what you see above. This is basically jQuery checking that the request is valid before attempting to POST any data. I'm pretty certain that the issue here is that Power BI sends `origin:null` which doesn't register as a valid origin even when your endpoint is configured to allow cross-origin requests. I would expect that line to be something like `origin:http://localhost` or something similar.

If you're using Chrome to develop and can install extensions, I installed Moesif Origin & CORS Changer (look for it in the Chrome web store) and disabled CORS and that fixed the issue. Would be great if Microsoft would look into this in a future version of the Power BI dev tools.

**Comment by swaswati** [comment]
Hi,
Can anyone share a sample code how you are calling your own REST API in update of custom visual? 
As I am new to this, so don't know much about coding part of visuals.

**Comment by jhegele** [comment]
@swaswati there are a lot of different ways to call a REST API in a custom visual since custom visuals are just TypeScript / JavaScript code. I'm familiar with jQuery and Javascript so that's what I tend to use. Here is how I generally make a `POST` request to an API (by no means is this the only or best way, though):

```javascript
$.ajax({
  url: apiEndpoint, // this is the url for the API endpoint
  type: 'POST',
  data: myDataHere, // this is the data I'm sending to the API endpoint
  dataType: 'json', // sending JSON to the API endpoint
  headers: {
    Authorization: myAuthInfoHere // my endpoint requires sending an Auth header
  },
  success: function(response) {
    // call succeeded, do stuff with the response here
    console.log('SUCCESS');
  },
  error: function(response) {
    // call failed, show an error message or something here
    console.log('ERROR');
  }
})
```

**Comment by swaswati** [comment]
@jhegele 
Thanks for help, but after importing jquery library and running above jquery code, i am getting error in browser side:
VM1273:483 Uncaught Error: Cannot create PowerBi jQuery plugin. jQuery was not loaded.
    at <anonymous>:483:15
    at Window.<anonymous> (<anonymous>:500:3)
    at <anonymous>:34290:20
    at Object.r [as injectJsCode] (visualhostcore.min.js:2)
    at i.loadWithoutResourcePackage (visualsandbox.min.js:1)
    at i.executeMessage (visualsandbox.min.js:1)
    at i.onMessageReceived (visualsandbox.min.js:1)
    at visualsandbox.min.js:1
    at e.invokeHandler (visualhostcore.min.js:2)
    at e.dispatchMessage (visualhostcore.min.js:2)

my code under visual.ts:

.....
  $.ajax({
  url: "https://learnwebcode.github.io/json-example/animals-1.json", // this is the url for the API endpoint
  type: 'GET',
//  data: myDataHere, // this is the data I'm sending to the API endpoint
  dataType: 'json', // sending JSON to the API endpoint
  /*headers: {
    Authorization: myAuthInfoHere // my endpoint requires sending an Auth header
  },*/
  success: function(response) {
    // call succeeded, do stuff with the response here
    console.log('SUCCESS'+response);
  },
  error: function(response) {
    // call failed, show an error message or something here
    console.log('ERROR'+response);
  }
})
.......

my tsconfig:
...
files:[
...
  "typings/index.d.ts",
    "node_modules/jquery/dist/jquery.js",
.....]

typings:
...
"globalDependencies": {
    "jquery": "registry:dt/jquery#1.10.0+20160316155526",
    "lodash": "registry:dt/lodash#4.14.0+20160830145422"
  }
...

pbiviz.json:

"externalJS": [
    "node_modules/powerbi-visuals-utils-dataviewutils/lib/index.js",
    "node_modules/jquery-powerbi/dist/jquery.powerbi.js",
    "node_modules/jquery/dist/jquery.min.js",
    "node_modules/jquery/dist/jquery.js",
    "src/jQueryAdaptor.js"

  ],



Do you have any idea around it?? How to resolve this?

**Comment by swaswati** [comment]
got it..it was configuration issue.
Thanks a lot!!

**Comment by Zahma** [comment]
@swaswati So is it working to call Ajax requests from update ?

**Comment by jay-pillai** [comment]
@Zahma  - The custom visuals run within a sandboxed iframe that is configured to not use the host details of the parent page. What this means is if your REST API will get origin as null, when the response comes back you will get a CORS error. Please change your REST API to respond with access-control-allow-origin to *.
