### ISSUE TITLE
Power BI Desktop executing old code

### ISSUE THREAD

**Issue by erapade** [microsoft/PowerBI-visuals#205]
My issue looks like [Issue166](https://github.com/Microsoft/PowerBI-visuals/issues/166), although this issue I have seen since February in all versions of Power BI Desktop

I downloaded an existing Power BI visual (in this case the Gantt visual). I did my changes, executed "pbiviz start" and validated/debugged in the Power BI Service "Code Visual". 
Then I created a package using the "pbiviz package" command. A new file was created in the "Dist" folder. I Loaded the newly build visual into a Power BI Desktop report, but now its only the old visual I see.

Do I need to change some version settings to make Power BI Desktop understand it shall look  for the new code?

**Comment by erapade** [comment]
#166

**Comment by erapade** [comment]
Anyone having any idea if the faults on my side (not reading the build manual), or it this is a tool problem?

**Comment by liprec** [comment]
Did you change the `guid` in the `pbiviz.json` file?

If you do not change it the Power BI service and desktop will download the running code based on the guid from the CDN network and **not** from the pbiviz file.

Just change the guid before you package your changed version and Power BI desktop will use that version.

-JP

**Comment by erapade** [comment]
Perfect. Thanks a lot. That helped. 
But to what shall I change. I changed from "Gantt1448688115699" to "Gantt1448688115700". 
And what are the guidlines for this guid as well as version numbers when submitting a Pull Request. Shall they have been changed before, or will they be changed by the one acting on the Pull Request?

**Comment by liprec** [comment]
When you create a new visual via pbiviz, the guid will be some 'default' guid with '_' instead of '-'.
As far as I know there is only one guideline when submitting a new visual to the Office Store: it should be a new one. And a generated one will guarantee that. 

But if you want to submit you changes via an PR to the Gantt repository, then you should keep the guid the same as the original. This guid and the download behavior will enable that all the visuals are automatic updated.

**Comment by erapade** [comment]
Thanks. 
I did some checking. A new visual will get a unique GUID, e.g:
`"guid": "newF514988586A346AC9971C6F423E477D2"`

**Will the following recommendations be correct?**
If changes are backwards compatible, the `guid`shall be the same. When will the visual then be updated? 1) as they are used, or 2) only when reports are edited, or 3) only when a visual is deleted and then re-imported in the report.

But if a change is not classified as totally backwards compatible (new parameters required, some re-sizing of visual objects, or changed behavior in auto coloring). Shall then the `guid`be changed. Depending on the behavior 1-3 above, that might be a god solution 

Anyway, There's a need for describing at least the need for changing the `guid` parameter in the `pbiviz.json` file. I looked through the instructions, and this is only mentioned in an other context in the FAQ file. I will update that. But there's also a need to update other parts of the instruction, so that developers understands how to test an updated visual as a package as well. This needs to be solved by someone more experienced than me

**Comment by liprec** [comment]
The CDN behavior is kicking in every time the visual is requested for the first time, so opening a report will download the visual code; the package embedded in the report is a fallback scenario if network is down e.g..

Because of this it is essential when enhancing a published visual that new functionality is aligned with the existing ones. Some things cannot easily been changed (like dataRoles names or capability names), but display names can. And use default values/behavior that doesn't alter the current visual too much. But keep for your visual the guid constant for all versions.

But you can test your package with the Power BI service easily by adding `?approvedResourcesDisabled=true` to the URL of a report. This will disable the automatic download and uses the uploaded package version. I don't believe that this is general documenten very well. Also this is not possible with Power BI desktop 😞 

BTW: this is only needed for 'official' custom visuals available in the Office Store and not necessary for all the other custom visuals; those are only embedded in the report and not available on the CDN network.
