### ISSUE TITLE
Static objects doesn't show up without error message

### ISSUE THREAD

**Issue by domoritz** [Microsoft/PowerBI-visuals#222]
I defined a static object but nothings shows up in powerbi.

```
"objects": {
        "rendering": {
            "displayName": "Rendering",
            "properties": {
                "svg": {
                    "displayName": "Use SVG",
                    "type": {
                        "bool": true
                    }
                }
            }
        }
    }
```

![image](https://user-images.githubusercontent.com/589034/28091378-6a54ec52-6644-11e7-891b-760118aef88a.png)

**Comment by AviSander** [comment]
Hello domoritz,
   So I've used your sample and went ahead and added it to a new visual I created, and it works. Please make sure you update the settings.ts so that it also populates your property and object.  Here's what how the file looks like after my change:
```
module powerbi.extensibility.visual {
    "use strict";
    import DataViewObjectsParser = powerbi.extensibility.utils.dataview.DataViewObjectsParser;

    export class VisualSettings extends DataViewObjectsParser {
      public dataPoint: dataPointSettings = new dataPointSettings();
      public rendering: renderingSettings = new renderingSettings();
      }

    export class dataPointSettings {
     // Default color
      public defaultColor: string = "";
     // Show all
      public showAllDataPoints: boolean = true;
     // Fill
      public fill: string = "";
     // Color saturation
      public fillRule: string = "";
     // Text Size
      public fontSize: number = 12;
     }

    export class renderingSettings {
      public svg: boolean = true;

     }

}
```

please note the renderingSettings class that was added.

We are still working on adding the ability for the settings file to update automatically after a change to the capabilities.json file, so that you would not need this step.

thx, avi

**Comment by domoritz** [comment]
Thanks Avi. Updating the class that extends the `DataViewObjectsParser` was indeed the problem. I think the issue for me was missing documentation and no error messages. Looking forward to the improvements in the future.
