### ISSUE TITLE
Manipulate other slices from within custom visual

### ISSUE THREAD

**Issue by eoglethorpe** [Microsoft/PowerBI-visuals#260]
Is it possible for a custom visual to disable the filtering settings from other slices?

What I am interested in doing is writing a visual that would disable all existing filtering from slices... not sure if this is possible.

**Comment by ABKimmel** [comment]
My understanding of the technology is that what you are wanting to do is currently impossible. Slicers change the data that gets sent to the individual visuals, rather than sending them a set of conditions with the data or with a set of filtered and a set of un-filtered data. This is most likely an efficiency move, since having each visual process the data set to apply the filters would create a lot of redundant overhead. So, unfortunately, it looks like what you want is impossible.

**Comment by uve** [comment]
Hello @eoglethorpe, @ABKimmel,
You can use **supportshighlight** option and handle any incoming selection in way.
 https://github.com/Microsoft/PowerBI-visuals/blob/master/Capabilities/Highlighting.md#supportshighlight

**Comment by ABKimmel** [comment]
@uve I believe he was asking whether you could override the filtering from a slicer, not from a selection in another visual. That would mean that the `supportshighlighting` option would not work for him.

**Comment by eoglethorpe** [comment]
Hey guys - thanks for your input. You're right, @ABKimmel in that this wouldn't work for me as I'm looking to change the values of existing slicers and not the filtering settings of incoming data.

In an ideal world what you'd be able to do is programmatically access other slicer objects and change their settings and then apply it back to the dashboard at large, but as you say, maybe this isn't quite possible.
