### ISSUE TITLE
"Displaying visuals in a single html page" instructions gives errors

### ISSUE THREAD

**Issue by kmhansen** [Microsoft/PowerBI-visuals#271]
When following the instructions on the "Displaying visuals in a single html" page, I get errors ("Object doesn't support property or method 'fieldDef'")

**Comment by abinashbandaru** [comment]
I am also facing the same issue.

**Comment by IgnatVilesov** [comment]
I've updated documentation [Displaying visuals in a single html page](https://github.com/Microsoft/PowerBI-visuals/wiki/Displaying-visuals-in-a-single-html-page).
Could you please try it again.

**Comment by sugarg** [comment]
The code at "Displaying visuals in a single html page" is not working. I am seeing Sales amount label at the top and country names at the bottom. No graph is showing up. Please if someone can help in resolving it.

![image](https://cloud.githubusercontent.com/assets/947278/15189550/2e343f54-1760-11e6-98fc-e4d6ed8d89e9.png)

**Comment by ignatvilesov** [comment]
@sugarg I’ve updated [documentation](https://github.com/Microsoft/PowerBI-visuals/wiki/Displaying-visuals-in-a-single-html-page). Could you please try it again.

**Comment by sugarg** [comment]
Its working now :). Thanks.

**Comment by sugarg** [comment]
I want to use id instead of class for rendering the chart but the style is not working with id (background color, font etc). Following are the changes that i did. I am doing something wrong?

1. Change style to refer to id instead of class
<style>
        #visual {
            'background-color' : 'white', 'padding' : '10px', 'margin' : '5px';
        }
    </style>

2. Change "visual" to id
<div id="visual"></div>

3. Changes createVisual() function
var element = $('#visual');


![image](https://cloud.githubusercontent.com/assets/947278/15258497/d4a5a8fe-1900-11e6-8a58-8b733227bc51.png)
