### ISSUE TITLE
.pbiviz creation Problems (VS 2013 and Power BI Desktop)

### ISSUE THREAD

**Issue by Xepherox** [Microsoft/PowerBI-visuals#315]
First I have tried to use the VisualTemplate.visx, but it seems that it do not work with VisualStudio2013? Is there also a version for VS2013? Or will there be a version in the future?

Second I have tried it with Power BI Desktop and wanted to use the "Developer Tools". But I do not find the button. I think the "Developer Tools" only works with the browser version?

How is it possible for me to build a .pbiviz with VS2013 or PowerBI Desktop?

**Comment by v-kazaki** [comment]
You are right, VSIX template doesn't support VS 2013. We recommend using [Visual Studio Community 2015](https://www.visualstudio.com/vs-2015-product-editions), it is free.

Developer tools can be used only with browser version, because Desktop version doesn't provide any debugging tools.

Note that .pbiviz package is simple zip file. So you can create your package using [Dev Tools](https://app.powerbi.com/devTools) once and change your package later as you want.
