### ISSUE TITLE
Can not make this work

### ISSUE THREAD

**Issue by justinlofley** [Microsoft/PowerBI-visuals#381]
I am seriously so frustrated with this right now. I will admit that I am not the most advanced user there is but I am far from not being able to use a computer. This has been the most frustrating experience though. I follow all of the instructions but simply can not make this thing work. 

when I try to run the npm install, I just get a screen that flips through names for hours on end with no resolution.

![image](https://cloud.githubusercontent.com/assets/17936414/14181204/47b2856a-f723-11e5-8cc3-1519c0a86c0b.png)

If I open the solution anyway I get all of the files and I can set the index.html as the start page

![image](https://cloud.githubusercontent.com/assets/17936414/14181259/7a402bf4-f723-11e5-8a8e-6568ae08adf1.png)

I set the build properties to No Build

![image](https://cloud.githubusercontent.com/assets/17936414/14181302/a3d74e5c-f723-11e5-9443-584a2dec640f.png)

Task runner does not open on it's own, but if I open it it shows nothing:

![image](https://cloud.githubusercontent.com/assets/17936414/14181339/c4007c9e-f723-11e5-88aa-ea6ab430bb4f.png)

and there are nothing but errors in the error list:

![image](https://cloud.githubusercontent.com/assets/17936414/14181362/d95c38e4-f723-11e5-9ffe-38760bc46ec6.png)

If I build the solution I get this:

![image](https://cloud.githubusercontent.com/assets/17936414/14181391/f1c3e044-f723-11e5-8f6a-478387bf8ca3.png)

what is my problem?

**Comment by larry609** [comment]
You're asking what you're doing wrong.  What you're doing wrong is that
you're asking the wrong question.

Ask us, who have been using MS products since 1981, and the question is:

Why does Micro$oft keep using developers and customers as its beta testers?

Answer: because, the company is, IMHO, as unscrupulous and arrogant as Bill
Gates.

One only has to know how Bill got the original PC DOS - and also have
watched his interview with Connie Chung (back in the day) to know all about
why MS products never, ever, not once, come to market as functional
products.

So - we just have to power through and help each other find temporary fixes.

More than likely, the problems may be in the code, but they are probably,
and primarily, in sloppy registry handling by MS.

If you do a registry snapshot, then install any MS product, then do another
snapshot, and then uninstall it, then look at all three, it is very
disheartening; however, this is true of almost every company (can you say
"McAfee"??).

**Comment by residentx10** [comment]
Larry, Please don't make this personal. This is software development. Take
a break and Justin you need to post into the PowerBI forums.

**Comment by justinlofley** [comment]
on the PowerBI website?

**Comment by ignatvilesov** [comment]
@justinlofley, Do you have gulp? You can install gulp using the command "npm install -g gulp".

**Comment by vtkalek** [comment]
Hi, Justin. By all signs you have forgotten to install gulp. 
When in root folder of PowerBI Try to run this command first : npm install -g gulp
Then npm install

If it'll not help then, you need to check what versions of gulp and NPM have been installed on your comp?

**Comment by justinlofley** [comment]
Thanks for the help guys, turns out it was a network issue, but it has been solved now.

**Comment by larry609** [comment]
I didn't make it personal I don't think. I just stated my experience with
Microsoft and also noted that we needed to persevere and work as a
community.

The fact is that I have yet to see it software company actually finished
product before creating a new version or a replacement. It's just a fact of
life.

And since I've been doing development ever since I majored in computer
engineering in 1967, I think I have some basis on which to save that.

Larry
sent from my Galaxy 4; please forgive typos and abbreviations
