### ISSUE TITLE
Github.io comments: Opening a URL in a new tab/window

### ISSUE THREAD

**Issue by uve** [microsoft/PowerBI-visuals#424]
Comments to https://microsoft.github.io/PowerBI-visuals/docs/how-to-guide/launching-url/

**Comment by elijoho** [comment]
Tried using the host.launchUrl() to open a link in a new window, but it only opened in a new tab. Did not find any information about where to add the '_blank'? Am I missing something or is it not possible to force the link to open in a new window?

**Comment by Guy-Moses** [comment]
@elijoho - The exact result of calling `host.launchUrl()` depends on PBI's environment: 

- On **Power BI web service**, it is similar to calling `window.open('https://www.your.url','_blank','noopener')`, which for most browsers means opening a new browser tab rather than a new window. 
 - On **Power BI Desktop** and **Power BI Mobile** apps, the OS will open the URL in the default browser, typically in a new tab if it is already open.

At any rate, there is no need to add '_blank' when using this API. Since the custom visual's code is sandboxed in a dedicated iframe, it doesn't have any control for top-level navigation, and this API call will always open the URL in a new tab or window, never replacing the current Power BI instance.

**Comment by imqscn** [comment]
@Guy-Moses Hi, I embeded an iframe in a Power BI report and used `host.launchUrl()` but it always open link in the iframe rather open a new browser tab. Do you have any idea about it?

I embeded iframe with an extension found in Marketplace.

**Comment by Guy-Moses** [comment]
Hi @imqscn (邱硕), 
If the Power BI report is hosted inside an iframe with sandbox attribute (and no "allow-popups" or similar), it's possible that `launchUrl()` will fail completely or open in the same iframe rather than in a new tab.

If this doesn't help, please use contact us through pbicvsupport@microsoft.com so we can discuss the details of your scenario.

**Comment by hjfrun** [comment]
Hi @Guy-Moses ,

I wrote a custom visual, and I used the `launchUrl()` function. But when we call this function. It will always prompt out a confirmation dialog the first time. Just like below:
![image](https://user-images.githubusercontent.com/4508489/67916284-27bd5680-fbd0-11e9-8338-eab46640fdaa.png)

The dialog will show all the full string of the url link. But this doesn't meet our requirements.

My questions is, Is there any way I can hide the url link in the dialog?
If I can't do this, can I add some parameters to the http request header or body?
Or how can I add a token to the external link?

Thank you!

**Comment by Guy-Moses** [comment]
Hi @hjfrun ,
The confirmation dialog is a required security measure - the user must be presented with the complete URL in order to give consent to the navigation. If your visual needs to communicate secret information to a server, there may be better ways to achieve this than using the `launchURL` API. Also, please note that a user could still use the browser's dev-tools or a network debugging tool such as Fiddler to see the complete URL, so even if it was possible to not display part of the URL, it still will not be safe.
Please contact custom visual development support team (pbicvsupport@microsoft.com) for more detailed assistance. If we have a better understanding of what are the requirements we may be able to offer a better solution.

**Comment by hjfrun** [comment]
@Guy-Moses Thanks, got it.
