### ISSUE TITLE
Github.io comments: API 2.1

### ISSUE THREAD

**Issue by uve** [microsoft/PowerBI-visuals#451]
Comments to https://microsoft.github.io/PowerBI-visuals/docs/changelog/api-2-1/

**Comment by bhavesh-jadav** [comment]
Hi @uve 

I have updated Visual API from 1.13.0 to v2.1.0 but I may have found some issue with the formatting of the date. I am using formatting utils to format the data in visual.

With v1.13.0 formatting is like below
![alt text](https://i.imgur.com/eGhzbuJ.png)

With v2.1.0 formatting is like below
![alt text](https://i.imgur.com/MQtZYHB.png)

I just changed the API version by running the `pbiviz update 2.1.0` command and did not do any changes in the code.

Is this change intentional?

**Comment by capono** [comment]
I'm wondering why this has not been reported or fixed yet. Version 2.1 and 2.2 break the "Fetch More Data" feature introduced in API 1.12. The values of each category are mixed up.

**Comment by capono** [comment]
@uve Can you give a update if there is someone working on that issue?

**Comment by uve** [comment]
@capono please try use new API 2.3

**Comment by capono** [comment]
@uve this is still broken.
