### ISSUE TITLE
Value Formatter

### ISSUE THREAD

**Issue by danieleperilli** [microsoft/PowerBI-visuals#56]
Will you include a Value Formatter in the new API?

**Comment by spatney** [comment]
I suppose we can easily. i'll add it in soon.

**Comment by sagarvadodaria** [comment]
Hi Sachin, 
Really need that valueFormatter. As per below, you can see that i have a column with value as date, but in the visualTransform function,   due to lack of formatting options for the value.  I see that format of the date has changed and have no way to make it as per the original source column format.  The second screenshot below shows the problem i face due to that.

![image](https://cloud.githubusercontent.com/assets/5859358/18117764/83896464-6f6e-11e6-9c29-f707839b8c2a.png)


![image](https://cloud.githubusercontent.com/assets/5859358/18117723/422b8b5a-6f6e-11e6-9b29-d2189c89ac0e.png)

**Comment by helen508light** [comment]
outdated. Now powerbi-visuals-utils-formattingutils are used for that tasks
