### ISSUE TITLE
could not find function "internalSaveWidget"

### ISSUE THREAD

**Issue by KleinhansDa** [microsoft/PowerBI-visuals#580]
1. The function _internalSaveWidget_ does not exist in 'htmlwidgets' (v1.5.1). There is _saveWidget_. 
2. The template _-t rhtml_ is generated within "C:/Windows/System32", is this how its supposed to be or can I change the output dir of _new_? 
3. I can not overwrite _script.r_

Thanks for the help!

Best,

David

**Comment by zBritva** [comment]
Hello @KleinhansDa 

1. In the `script.r` file you should see `source('./r_files/flatten_HTML.r')`. The function `internalSaveWidget` is defined inside of './r_files/flatten_HTML.r' file. The function calls `saveWidget` from `htmlwidgets`. What is wrong in your case? Are any errors on `npm start` command?

2. You can call `pbiviz new <visualname> -t rhtml` from any directory if you installed `powerbi-visuals-tools` in [global](https://docs.npmjs.com/downloading-and-installing-packages-globally). Tool creates folder for visual's projects files. If you call it from `C:/Windows/System32` it creates in the system catalog. And it's not good idea. [Change current directory](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/cd) to you workspace where you can keep and save you visual project.

3. Could you explain what do you try to do? You can write your R code in the `script.r` file and give output by calling `internalSaveWidget(p, 'out.html');`, but you can't rename the file name because tools looks to `script.r` file.

**Comment by KleinhansDa** [comment]
Hello @zBritva!

I think the confusion came from the official documentation. Since `script.r` is an R file I thought `internalSaveWidget` was an R function.

By now I successfully created a custom visual!

An article called "_How to create R custom visual (html) in PowerBI_" helped me a lot!

Thanks for the reply!
