### ISSUE TITLE
"step by step tutorial" is actually mostly just - "here's the code, go figure"

### ISSUE THREAD

**Issue by Mike-Honey** [microsoft/PowerBI-visuals#59]
The intro to the "Developing Your First PowerBI Visual" section of Readme.md promises a "step by step tutorial", but I'm not following the flow.  The "Setting Up Environment" is good, but the "Building Bar Chart" seems little more then "here's the code, go figure".

Some of the things I'd expect to see in a coding tutorial:
- the objective of each step and the final solution, this is in some sections but not all
- set up steps (was that implied by the earlier "Environment" section?)
- context eg where are we working and on which files?
- steps to test the code at the end of each step - how to run it and what the expected result is

Perhaps our core definition of a "tutorial" differs?  My expectation is that a fairly competent coder can start from scratch and follow the instructions methodically (with some side references etc) and build a viable working app.

**Comment by TonyGaul** [comment]
Hi, I agree with your comments Mike.  I'm an experienced, traditional Microsoft BI stack developer (SQL, MDX, DAX, VB/VBA) trying to get my head around this step by step tutorial, but there is an assumption that you are an experienced web / JS developer familiar with web development and testing lifecycle.  I would like to see documentation that doesn't assume you have a strong web background which would really help increase adoption of this really great feature of Power BI. Or alternately Microsoft should give some guidance on the skills required to be able to follow the documentation and build a custom visual.

For example I followed the steps then all of a sudden at step 7. Adding External Libraries, I am shown what looks like a Visual Studio screen shot and a message saying download external libraries to the external folder.  Many assumptions here and no mention of Visual Studio so far.  So a bit more info on the IDE would be good.  A link to an overview of the libraries etc. Can we use other editors such as Notepad++ with plugins or should we use Visual Studio.  

I'd love to see a more detailed guide as a higher priority over other features to speed up the adoption of this Power BI feature, otherwise many businesses will be left waiting for the monthly release of a custom visual which doesn't quite fit the requirements, still debating why Tableau visuals are better... or perhaps are left to the mercy of high profile, high cost Viz developers OK!

**Comment by demetrioi** [comment]
I agree too. Should detail more the process of creating the graphical part of the visual.

**Comment by whyvez** [comment]
There are lots of potential with PowerBI and the best way to get adoption will be to improve the docs. Just like many projects have proven; once you have the developers on board nothing will stop you. We have moved to Tableau for our project which supports better printing capabilities which we needed.  The down side of Tableau is there are no direct path to extensibility.

**Comment by spatney** [comment]
@Mike-Honey  Makes sense, and we can definitely improve that. @TonyGaul, you don't need any IDE, the screenshot was just to show the folder structure, but agreed that we could clarify that a bit better.  Also, you are free to use any JS library and intentionally don't provide any links are it depends entirely on the visualization you are trying to build. We do have a detailed documentation/example on using an external library to use in a visual. 

@demetrioi. I think the graphical part of the visual is up-to-you, and thus the lack of emphasis. I suppose we could include a few links on how people in general create visualizations for the web, but this tool is to enable embedding of these with power bi, and providing APIs to communicate with the power bi host.

**Comment by Tameshiwari** [comment]
Bar Chart mainly deals with d3.js code to reproduce bar chart. I used the library in a lot of Web data visualization [including Angular directives + components] and I must admit it's a tool I really can avoid. Possibilities are endless... Needless to say I believe Microsoft has taken a great initiative. IMHO the key point which wasn't emphasized enough was how to take existing d3.js code and manage to reshape it so it could be fully compatible with Power BI lifecycle context. I guess most realized it wasn't just a Cut & Paste pattern. Jon Gallant brought a good approach with liquidFillGauge demo. Also old CORE demo is now deprecated. Some pieces of code samples have been migrated but not all. So it's up to us to figure out the logic between the two versions in order to take full advantage. Like importing microsoft.powerbi.visuals... That's where the fun begins...

**Comment by Tameshiwari** [comment]
RE: Makes sense, and we can definitely improve that....
Well then what are you waiting for!!!???
It's been over 7 months now... yet no major improvement has been done on documentation. Same old revamped barChart code sample... I don't know but I'm getting the strange feeling that submitting idea in this forum is just a big waste of time... I wish I'm wrong though poor follow up + lack of mature documented information raise some skepticism

**Comment by helen508light** [comment]
outdated
