### ISSUE TITLE
d3.v4.js not working

### ISSUE THREAD

**Issue by emmasaunders** [microsoft/PowerBI-visuals#98]
I've been trying to get d3.v4 working with powerBI  (http://stackoverflow.com/questions/40283005/typescript-d3-and-powerbi-how-do-i-get-typescript-to-talk-to-d3-v4). 

Instructions here (https://github.com/Microsoft/PowerBI-visuals/blob/master/Tutorial/ExternalLibraries.md) say D3 v 3.5 is pre-loaded. However, when I create a new project folder (pbiviz new myNewProject), I cannot use d3 commands in visual.ts. Similarly, when I add d3.v4.js into a new folder called External, reference the file in tsconfig.json, d3 commands are not recognised. Is there something else I have to do in visual.ts to get D3 working?

The instructions that worked for me are here: https://github.com/Microsoft/PowerBI-visuals/blob/master/Tutorial/Typings.md - however that has installed support for V3, not V4.

**Comment by Venex** [comment]
It might have something to do with PowerBI filtering uit global variables. This is the issue Im experiencing'.
Place a debugger statement in your code and when breaking, scroll all the way down.
Right here, you'll find code for "overwrite global variables with window values for PowerBI libraries".
My libraries are excluded there, which I find a little harsh

**Comment by r1sc** [comment]
To anyone else experiencing this issue.
As @Venex is saying, this error stems from the fact that PowerBI replaces the global scope as in 
```var window = this;```

I tried to add three.js from npm and got the same issue.
Debugging i noticed that while three gets loaded correctly, it attaches itself to the made-up window object ```window``` instead of ```this.window```. To bring it back into global scope I just added this line to a file I load right after my external library: ```this.window.THREE = window.THREE;```

You would probably need to make something similar to get d3 working.

**Comment by KristofferBerge** [comment]
Any update on this? The tutorial states that d3@.4.9.1 should be installed which leads to a lot of frustration since no errors are thrown. If there is no workaround for this, the tutorial should at least be updated to use d3@3.5.17 so people new to this can complete the tutorial.

https://github.com/Microsoft/PowerBI-visuals/blob/master/Tutorial/ExternalLibraries.md

**Comment by howlowck** [comment]
I posted [a solution](https://github.com/Microsoft/PowerBI-visuals/issues/142#issuecomment-381160269) on #142 that might solve your issue.

**Comment by uve** [comment]
Please update your visual to API 3.2.0 and D3.js to v5.x. It should solve the issue.
